# (c) 2016 Rahmat M. Samik-Ibrahim
# REV01 Thu Aug 25 13:59:01 WIB 2016
# START Fri Jul 15 16:08:58 WIB 2016

all:	190.pdf 

190.pdf:  190.tex
	pdflatex 190

clean:
	chmod	644 *.pdf
	rm -f *.aux *.log *.idx *.toc *.bbl *.blg
	rm -f *.nav *.out *.snm *.vrb

